//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace System.Properties {
    using System;
    using System.Reflection;
    
    
    /// <summary>
    ///    A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        internal Resources() {
        }
        
        /// <summary>
        ///    Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("NETStandard.WindowsCE.Properties.Resources", typeof(Resources).GetTypeInfo().Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///    Overrides the current thread's CurrentUICulture property for all
        ///    resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to One or more errors occurred..
        /// </summary>
        public static string AggregateException_ctor_DefaultMessage {
            get {
                return ResourceManager.GetString("AggregateException_ctor_DefaultMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to An element of innerExceptions was null..
        /// </summary>
        public static string AggregateException_ctor_InnerExceptionNull {
            get {
                return ResourceManager.GetString("AggregateException_ctor_InnerExceptionNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to The serialization stream contains no inner exceptions..
        /// </summary>
        public static string AggregateException_DeserializationFailure {
            get {
                return ResourceManager.GetString("AggregateException_DeserializationFailure", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to {0}{1}---&gt; (Inner Exception #{2}) {3}{4}{5}.
        /// </summary>
        public static string AggregateException_ToString {
            get {
                return ResourceManager.GetString("AggregateException_ToString", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Destination array is not long enough to copy all the items in the collection. Check array index and length..
        /// </summary>
        public static string Arg_ArrayPlusOffTooSmall {
            get {
                return ResourceManager.GetString("Arg_ArrayPlusOffTooSmall", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to The lower bound of target array must be zero..
        /// </summary>
        public static string Arg_NonZeroLowerBound {
            get {
                return ResourceManager.GetString("Arg_NonZeroLowerBound", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Only single dimensional arrays are supported for the requested action..
        /// </summary>
        public static string Arg_RankMultiDimNotSupported {
            get {
                return ResourceManager.GetString("Arg_RankMultiDimNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to An item with the same key has already been added. Key: {0}.
        /// </summary>
        public static string Argument_AddingDuplicate {
            get {
                return ResourceManager.GetString("Argument_AddingDuplicate", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Target array type is not compatible with the type of items in the collection..
        /// </summary>
        public static string Argument_InvalidArrayType {
            get {
                return ResourceManager.GetString("Argument_InvalidArrayType", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to The specified item does not exist in this KeyedCollection..
        /// </summary>
        public static string Argument_ItemNotExist {
            get {
                return ResourceManager.GetString("Argument_ItemNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to The specified threshold for creating dictionary is out of range..
        /// </summary>
        public static string ArgumentOutOfRange_InvalidThreshold {
            get {
                return ResourceManager.GetString("ArgumentOutOfRange_InvalidThreshold", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Non-negative number required..
        /// </summary>
        public static string ArgumentOutOfRange_NeedNonNegNum {
            get {
                return ResourceManager.GetString("ArgumentOutOfRange_NeedNonNegNum", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Index cannot be negative..
        /// </summary>
        public static string IndexCannotBeNegative {
            get {
                return ResourceManager.GetString("IndexCannotBeNegative", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Constructor only supports either a Reset, Add, or Remove action..
        /// </summary>
        public static string MustBeResetAddOrRemoveActionForCtor {
            get {
                return ResourceManager.GetString("MustBeResetAddOrRemoveActionForCtor", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Collection is read-only..
        /// </summary>
        public static string NotSupported_ReadOnlyCollection {
            get {
                return ResourceManager.GetString("NotSupported_ReadOnlyCollection", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Cannot change ObservableCollection during a CollectionChanged event..
        /// </summary>
        public static string ObservableCollectionReentrancyNotAllowed {
            get {
                return ResourceManager.GetString("ObservableCollectionReentrancyNotAllowed", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Reset action must be initialized with index -1..
        /// </summary>
        public static string ResetActionRequiresIndexMinus1 {
            get {
                return ResourceManager.GetString("ResetActionRequiresIndexMinus1", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Reset action must be initialized with no changed items..
        /// </summary>
        public static string ResetActionRequiresNullItem {
            get {
                return ResourceManager.GetString("ResetActionRequiresNullItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to The timeout must represent a value between -1 and Int32.MaxValue, inclusive..
        /// </summary>
        public static string SpinWait_SpinUntil_TimeoutWrong {
            get {
                return ResourceManager.GetString("SpinWait_SpinUntil_TimeoutWrong", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Constructor supports only the &apos;{0}&apos; action..
        /// </summary>
        public static string WrongActionForCtor {
            get {
                return ResourceManager.GetString("WrongActionForCtor", resourceCulture);
            }
        }
    }
}
