//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace System.Properties {
    using System;
    using System.Reflection;
    
    
    /// <summary>
    ///    A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        internal Resources() {
        }
        
        /// <summary>
        ///    Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("NETStandard.WindowsCE.Properties.Resources", typeof(Resources).GetTypeInfo().Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///    Overrides the current thread's CurrentUICulture property for all
        ///    resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to One or more errors occurred..
        /// </summary>
        public static string AggregateException_ctor_DefaultMessage {
            get {
                return ResourceManager.GetString("AggregateException_ctor_DefaultMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to An element of innerExceptions was null..
        /// </summary>
        public static string AggregateException_ctor_InnerExceptionNull {
            get {
                return ResourceManager.GetString("AggregateException_ctor_InnerExceptionNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to The serialization stream contains no inner exceptions..
        /// </summary>
        public static string AggregateException_DeserializationFailure {
            get {
                return ResourceManager.GetString("AggregateException_DeserializationFailure", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to {0}{1}---&gt; (Inner Exception #{2}) {3}{4}{5}.
        /// </summary>
        public static string AggregateException_ToString {
            get {
                return ResourceManager.GetString("AggregateException_ToString", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to The timeout must represent a value between -1 and Int32.MaxValue, inclusive..
        /// </summary>
        public static string SpinWait_SpinUntil_TimeoutWrong {
            get {
                return ResourceManager.GetString("SpinWait_SpinUntil_TimeoutWrong", resourceCulture);
            }
        }
    }
}
